### ISSUE TITLE
Won't load, missing class

### ISSUE THREAD

**Issue by kurrier** [wizecore/graylog2-output-syslog#20]
Fails to load plugin with the following error:

java.lang.NoClassDefFoundError: Could not initialize class org.graylog2.syslog4j.Syslog
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2216) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4147) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5053) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRegistry.getOutputForIdAndStream(OutputRegistry.java:102) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRouter.getMessageOutputsForStream(OutputRouter.java:42) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRouter.getStreamOutputsForMessage(OutputRouter.java:62) ~[graylog.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:132) ~[graylog.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:51) ~[graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.graylog2.syslog4j.Syslog

**Comment by huksley** [comment]
Which version of Graylog you are using?
Which version of plugin you are using? Compiled by yourself or using one from releases page?

**Comment by kurrier** [comment]
Graylog 2.3.2 and 2.4.0
Plugin version 2.3.1 and 2.1.1b - Tried jar release and self compiled, same results all around.

**Comment by kurrier** [comment]
Adjusted settings [pom.xml](https://github.com/wizecore/graylog2-output-syslog/blob/f6f994afb02836c93759eabc41c731c08b067fc4/pom.xml#L26)
`<graylog2.version>2.3.1</graylog2.version>
<graylog2.syslog4j.version>0.9.55</graylog2.syslog4j.version>`

To:
`<graylog2.version>2.4.0</graylog2.version>
<graylog2.syslog4j.version>0.9.60</graylog2.syslog4j.version>`

Then loading [syslog4j-0.9.60](https://github.com/graylog-labs/syslog4j-graylog2/releases) directly into java classpath resolved the issue

**Comment by huksley** [comment]
Sorry for delay. Strange what you needed to add  syslog4j-0.9.60 JAR into classpath. 
As far as I can see, graylog 2.4.0 JAR (one in docker) includes syslog4j....
