### ISSUE TITLE
Syslog TLS connection

### ISSUE THREAD

**Issue by anyon486** [wizecore/graylog2-output-syslog#42]
Hi,

When a try to configure log forwarding to an external syslog server via TCP-SSL as follows, i obtain the following stack trace.

![image](https://user-images.githubusercontent.com/8733819/102806976-1e87de00-43be-11eb-896a-d275618b98ca.png)

`javax.net.ssl|SEVERE|CE|SyslogWriter: tcp-ssl_172.25.55.101_2514_transparent|2020-12-21 18:53:03.961 CET|Logger.java:765|Fatal (CERTIFICATE_UNKNOWN): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target (
"throwable" : {
  sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
        at sun.security.validator.Validator.validate(Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:638)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
        at sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:149)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1143)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1054)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:394)
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:708)
        at sun.security.ssl.SSLSocketImpl.access$100(SSLSocketImpl.java:72)
        at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:961)
        at java.io.OutputStream.write(OutputStream.java:75)
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.write(TCPNetSyslogWriter.java:153)
        at org.graylog2.syslog4j.impl.AbstractSyslogWriter.run(AbstractSyslogWriter.java:94)
        at java.lang.Thread.run(Thread.java:748)
  Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
        ... 23 more}
)`

Could you please help me to solve this issue?
Thanks in advance.
M.

**Comment by anyon486** [comment]
I figured out the issue. The plugin seems to not consider the parameters keystore, keystorePasswords, truststore and truststorePassword, therefore I set them on JVM as follows and it works:

-Djavax.net.ssl.trustStore=/usr/share/graylog/ownca/truststore.jks 
-Djavax.net.ssl.trustStorePassword=password 
-Djavax.net.ssl.keyStore=/usr/share/graylog/ownca/keystore.jks 
-Djavax.net.ssl.keyStorePassword=password

Best regards.
M.

**Comment by huksley** [comment]
Hi, thanks for a bug report.

As far as I understand, all SSL related parameters are configured on the Syslog output but it does not work until you set them also in JVM arguments, right? 

I will take a look at this, probably some incompatibility changes after upgrading to the newer version of Graylog (and bundled syslog library)

**Comment by anyon486** [comment]
Hi,
Yes, you got right. 
Thanks in advance.
Best regards.

**Comment by XaHDpE** [comment]
@anyon486 hello!

can you please advise if the plugin supports TLS v1.2 or only SSL.
from what i see, only SSL is supported, 

thanks!

**Comment by anyon486** [comment]
Hi!

TLS is also supported.
Regards.
M.

**Comment by huksley** [comment]
Resolved in latest version, works fine with Syslog-ng
