### ISSUE TITLE
Not working with Graylog v3.3.5

### ISSUE THREAD

**Issue by smaug1985** [wizecore/graylog2-output-syslog#46]
Is not working with Graylog v3.3.5.

I haven the following error:

`2021-04-14T11:40:07.431+02:00 ERROR [OutputRegistry] Unable to fetch output 60759737bdb60a249071c494, fault #4
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Output type is not supported: com.wizecore.graylog2.plugin.SyslogOutput
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRegistry.getOutputForIdAndStream(OutputRegistry.java:102) [graylog.jar:?]
        at org.graylog2.outputs.OutputRouter.getMessageOutputsForStream(OutputRouter.java:42) [graylog.jar:?]
        at org.graylog2.outputs.OutputRouter.getStreamOutputsForMessage(OutputRouter.java:62) [graylog.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:132) [graylog.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor.onEvent(OutputBufferProcessor.java:51) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.IllegalArgumentException: Output type is not supported: com.wizecore.graylog2.plugin.SyslogOutput
        at org.graylog2.outputs.MessageOutputFactory.fromStreamOutput(MessageOutputFactory.java:64) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRegistry.launchOutput(OutputRegistry.java:143) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRegistry$2.call(OutputRegistry.java:137) ~[graylog.jar:?]
        at org.graylog2.outputs.OutputRegistry$2.call(OutputRegistry.java:133) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[graylog.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[graylog.jar:?]
        ... 10 more
`

Any update schedule?

Thank you.

**Comment by huksley** [comment]
See 3.3.2 or better yet 4.0.8 version published 

Apologies for the delay https://github.com/wizecore/graylog2-output-syslog/releases/tag/v4.0.8
