### ISSUE TITLE
SSL/TSL over TCP without mutual authentication

### ISSUE THREAD

**Issue by nltommynl** [wizecore/graylog2-output-syslog#55]
With Graylog 3 and plugin version 3.3.0, it was possible to connect to a syslog server over TCP with TLS. In the configuration, the following fields were filled:

- Title
- Message dispatch protocol
- Syslog host
- Syslog port
- Message format

The other fields for defining a key and truststore, among others, were empty.

Now we upgraded to Graylog 4.3.9 with plugin version 4.2.6 and now we receive the following error message:

`2022-11-15T08:59:01.593+01:00 INFO  [CustomSSLSyslogWriter] Reading
2022-11-15T08:59:01.593+01:00 WARN  [CustomSSLSyslogWriter] Failed to create SSLContext:  (No such file or directory)
java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_352]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_352]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_352]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_352]
        at com.wizecore.graylog2.plugin.ssl.CustomSSLSyslogWriter.createSSLContext(CustomSSLSyslogWriter.java:37) ~[graylog-output-syslog-4.2.6.jar:?]
        at com.wizecore.graylog2.plugin.ssl.CustomSSLSyslogWriter.obtainSocketFactory(CustomSSLSyslogWriter.java:78) [graylog-output-syslog-4.2.6.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.createSocket(TCPNetSyslogWriter.java:58) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.getSocket(TCPNetSyslogWriter.java:99) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.write(TCPNetSyslogWriter.java:135) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslog.write(TCPNetSyslog.java:63) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.write(AbstractSyslog.java:317) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:253) [graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:145) [graylog.jar:?]
        at com.wizecore.graylog2.plugin.StructuredSender.send(StructuredSender.java:62) [graylog-output-syslog-4.2.6.jar:?]
        at com.wizecore.graylog2.plugin.SyslogOutput.write(SyslogOutput.java:265) [graylog-output-syslog-4.2.6.jar:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:193) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
2022-11-15T08:59:01.593+01:00 ERROR [OutputBufferProcessor] Error in output [class com.wizecore.graylog2.plugin.SyslogOutput].
java.lang.RuntimeException: Failed to create SSLContext:  (No such file or directory)
        at com.wizecore.graylog2.plugin.ssl.CustomSSLSyslogWriter.obtainSocketFactory(CustomSSLSyslogWriter.java:81) ~[?:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.createSocket(TCPNetSyslogWriter.java:58) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.getSocket(TCPNetSyslogWriter.java:99) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslogWriter.write(TCPNetSyslogWriter.java:135) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.net.tcp.TCPNetSyslog.write(TCPNetSyslog.java:63) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.write(AbstractSyslog.java:317) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:253) ~[graylog.jar:?]
        at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:145) ~[graylog.jar:?]
        at com.wizecore.graylog2.plugin.StructuredSender.send(StructuredSender.java:62) ~[?:?]
        at com.wizecore.graylog2.plugin.SyslogOutput.write(SyslogOutput.java:265) ~[?:?]
        at org.graylog2.buffers.processors.OutputBufferProcessor$1.run(OutputBufferProcessor.java:193) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:180) [graylog.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_352]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_352]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_352]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_352]
Caused by: java.io.FileNotFoundException:  (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_352]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_352]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_352]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_352]
        at com.wizecore.graylog2.plugin.ssl.CustomSSLSyslogWriter.createSSLContext(CustomSSLSyslogWriter.java:37) ~[?:?]
        at com.wizecore.graylog2.plugin.ssl.CustomSSLSyslogWriter.obtainSocketFactory(CustomSSLSyslogWriter.java:78) ~[?:?]
        ... 16 more`

I believe (based on the code) this error message is generated because the key store field is left empty. Is this correct? And does this imply that this plugin only supports (TLS) mutual authentication?

**Comment by huksley** [comment]
> 2022-11-15T08:59:01.593+01:00 INFO  [CustomSSLSyslogWriter] Reading "_____???____"

It seems like, in your case, keyStore field was empty. It is required for SSL and should specify a path to the keystore with a private key to enable SSL
